# - icon: "icon ion-coffee"
#   title: "Branding"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"

- icon: "ion-ios-monitor-outline"
  title: "Web Design"
  content: "For beautful responsive web designs"  

# - icon: "ion-image"
#   title: "App Design"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
  
- icon: "ion-bug"
  title: "Debugging"
  content: "I can review broken code and debug issues"
  
# - icon: "ion-headphone"
#   title: "Logo Design"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
  
- icon: "ion-document-text"
  title: "Development"
  content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"

- icon: "ion-happy"
  title: "Brand Identity"
  content: "Follow my blog for branding tips as I put my marketing knowledge to the test, to better build Brand Me 2.0"
  
# - icon: "ion-earth"
#   title: "Brand Identity"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"  
