# - icon: "icon ion-coffee"
#   title: "Branding"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"

- icon: "ion-ios-monitor-outline"
  title: "Web Design"
  content: "For beautiful responsive web designs"  

# - icon: "ion-image"
#   title: "App Design"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
  
- icon: "ion-bug"
  title: "Debugging"
  content: "Review broken code and debug issues"
  
# - icon: "ion-headphone"
#   title: "Logo Design"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
  
- icon: "ion-document-text"
  title: "Development"
  content: "Full stack web developer"

- icon: "ion-happy"
  title: "Brand Identity"
  content: "Follow my blog for marketing and web programming tips as I discuss trends to overall improve brand identity."
  
# - icon: "ion-earth"
#   title: "Brand Identity"
#   content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"  
